pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
		maven {
			name = 'Seedfinding'
			url = 'https://maven.seedfinding.com/'
		}
		maven {
			name = 'Seedfinding Snapshots'
			url = 'https://maven-snapshots.seedfinding.com/'
		}
		maven {
			name = 'LattiCG'
			url = 'https://maven.latticg.com/'
		}
	}
}

// Should match your modid
rootProject.name = 'zephyr'
