package com.zephyr.client.configplusgui.secretsettings.bettermovement;

import net.minecraft.client.Minecraft;

/**
 * Master switch for the hidden "Better Movement" feature set, toggled from the secret
 * "???" screen (see {@link com.zephyr.client.configplusgui.screen.SecretGuiScreen}). When
 * enabled it delegates per-tick processing to the individual helpers it bundles:
 * {@link Aerodynamics} (sprint air-acceleration), {@link Dash} (mid-air sneak dash),
 * {@link DoubleJump}, {@link WaveDash}, and {@link Glide}. It also keeps {@link NoFall}'s
 * tick grace active so falls generated by these moves don't apply fall damage.
 */
public final class BetterMovement {
    public static boolean enabled;

    private BetterMovement() {
    }

    /** Enables or disables the whole Better Movement set, wiring up/down each helper. */
    public static void setEnabled(boolean value) {
        if (enabled == value) return;
        enabled = value;
        if (enabled) {
            onEnable();
        } else {
            onDisable();
        }
    }

    /** Enables every Better Movement helper. */
    public static void onEnable() {
        Aerodynamics.onEnable();
        Dash.onEnable();
        DoubleJump.onEnable();
        WaveDash.onEnable();
        Glide.onEnable();
    }

    /** Disables every Better Movement helper and resets the no-fall grace. */
    public static void onDisable() {
        Aerodynamics.onDisable();
        Dash.onDisable();
        DoubleJump.onDisable();
        WaveDash.onDisable();
        Glide.onDisable();
        NoFall.noFallTicks = 0;
    }

    /** Forwards the client tick to each helper and keeps the no-fall grace topped up. */
    public static void tick(Minecraft client) {
        if (!enabled) return;

        Aerodynamics.tick(client);
        Dash.tick(client);
        DoubleJump.tick(client);
        WaveDash.tick(client);
        Glide.tick(client);

        NoFall.noFallTicks = 2;
    }
}
