package com.zephyr.client.commands;

import com.zephyr.client.configplusgui.config.GlobalConfig;
import com.zephyr.client.configplusgui.hud.Corner;
import com.zephyr.client.configplusgui.hud.HudMode;
import com.zephyr.client.configplusgui.hud.ThemeColor;

import java.util.List;
import java.util.Locale;

/**
 * Port of {@code cconfig}. In clientcommands this was generated by BetterConfig.
 * Here we expose Zephyr's {@link GlobalConfig} keys so users can inspect/set them
 * via {@code .z config}. Also supports {@code config} alias as {@code cconfig}.
 */
public final class ConfigCommand extends Command {
    public static final ConfigCommand INSTANCE = new ConfigCommand();

    private ConfigCommand() {
        super("config", "View/set client configs: .z config <list|get <key>|set <key> <value>> (alias: cconfig)");
    }

    @Override
    public List<String> suggest(String[] args) {
        if (args.length == 1) return List.of("list", "get", "set");
        if (args.length == 2 && (args[0].equalsIgnoreCase("get") || args[0].equalsIgnoreCase("set"))) {
            return List.of("hotkeyPopups", "useCustomColor", "customHue", "customSaturation", "customValue",
                    "menuAnimationSpeed", "notificationCorner", "notificationLifetime", "hudMode", "autosaveInterval",
                    "keybindConflictWarnings", "discordPresence", "stealthMode", "themeColor");
        }
        if (args.length == 3 && args[0].equalsIgnoreCase("set")) {
            String key = args[1].toLowerCase(Locale.ROOT);
            return switch (key) {
                case "hotkeypopups", "usecustomcolor", "keybindconflictwarnings", "discordpresence", "stealthmode" -> List.of("true", "false");
                case "hudmode" -> List.of("OFF", "LEGACY", "MODERN");
                case "notificationcorner" -> List.of("TOP_LEFT", "TOP_RIGHT", "BOTTOM_LEFT", "BOTTOM_RIGHT");
                case "themecolor" -> {
                    var vals = ThemeColor.values();
                    java.util.ArrayList<String> n = new java.util.ArrayList<>();
                    for (var v : vals) n.add(v.name());
                    yield n;
                }
                default -> List.of();
            };
        }
        return List.of();
    }

    @Override
    public void execute(String[] args) {
        if (args.length == 0) {
            CommandManager.sendMessage("Usage: .z config <list|get <key>|set <key> <value>>");
            return;
        }
        String sub = args[0].toLowerCase(Locale.ROOT);
        switch (sub) {
            case "list" -> list();
            case "get" -> {
                if (args.length < 2) {
                    CommandManager.sendMessage("Usage: .z config get <key>");
                    return;
                }
                get(args[1]);
            }
            case "set" -> {
                if (args.length < 3) {
                    CommandManager.sendMessage("Usage: .z config set <key> <value>");
                    return;
                }
                String key = args[1];
                String value = String.join(" ", java.util.Arrays.copyOfRange(args, 2, args.length));
                set(key, value);
            }
            default -> CommandManager.sendMessage("Usage: .z config <list|get <key>|set <key> <value>>");
        }
    }

    private void list() {
        CommandManager.sendMessage("Configs: hotkeyPopups=" + GlobalConfig.hotkeyPopups.get()
                + ", useCustomColor=" + GlobalConfig.useCustomColor.get()
                + ", hudMode=" + GlobalConfig.hudMode.get()
                + ", notificationCorner=" + GlobalConfig.notificationCorner.get()
                + ", themeColor=" + GlobalConfig.themeColor()
                + ", autosaveInterval=" + GlobalConfig.autosaveInterval.get()
                + ", discordPresence=" + GlobalConfig.discordPresence.get()
                + ", stealthMode=" + GlobalConfig.stealthMode.get());
    }

    private void get(String key) {
        String lk = key.toLowerCase(Locale.ROOT);
        String val = switch (lk) {
            case "hotkeypopups" -> String.valueOf(GlobalConfig.hotkeyPopups.get());
            case "usecustomcolor" -> String.valueOf(GlobalConfig.useCustomColor.get());
            case "customhue" -> String.valueOf(GlobalConfig.customHue.get());
            case "customsaturation" -> String.valueOf(GlobalConfig.customSaturation.get());
            case "customvalue" -> String.valueOf(GlobalConfig.customValue.get());
            case "menuanimationspeed" -> String.valueOf(GlobalConfig.menuAnimationSpeed.get());
            case "notificationcorner" -> String.valueOf(GlobalConfig.notificationCorner.get());
            case "notificationlifetime" -> String.valueOf(GlobalConfig.notificationLifetime.get());
            case "hudmode" -> String.valueOf(GlobalConfig.hudMode.get());
            case "autosaveinterval" -> String.valueOf(GlobalConfig.autosaveInterval.get());
            case "keybindconflictwarnings" -> String.valueOf(GlobalConfig.keybindConflictWarnings.get());
            case "discordpresence" -> String.valueOf(GlobalConfig.discordPresence.get());
            case "stealthmode" -> String.valueOf(GlobalConfig.stealthMode.get());
            case "themecolor" -> String.valueOf(GlobalConfig.themeColor());
            default -> null;
        };
        if (val == null) CommandManager.sendMessage("Unknown config key: " + key);
        else CommandManager.sendMessage(key + " = " + val);
    }

    private void set(String key, String value) {
        String lk = key.toLowerCase(Locale.ROOT);
        try {
            switch (lk) {
                case "hotkeypopups" -> GlobalConfig.setHotkeyPopupsEnabled(parseBool(value));
                case "usecustomcolor" -> GlobalConfig.setUseCustomColor(parseBool(value));
                case "customhue" -> { GlobalConfig.customHue.set(Double.parseDouble(value)); GlobalConfig.save(); }
                case "customsaturation" -> { GlobalConfig.customSaturation.set(Double.parseDouble(value)); GlobalConfig.save(); }
                case "customvalue" -> { GlobalConfig.customValue.set(Double.parseDouble(value)); GlobalConfig.save(); }
                case "menuanimationspeed" -> GlobalConfig.setAnimationSpeed(Double.parseDouble(value));
                case "notificationcorner" -> GlobalConfig.setNotificationCorner(Corner.valueOf(value.toUpperCase(Locale.ROOT)));
                case "notificationlifetime" -> GlobalConfig.setNotificationHoldSeconds(Double.parseDouble(value));
                case "hudmode" -> GlobalConfig.setHudMode(HudMode.valueOf(value.toUpperCase(Locale.ROOT)));
                case "autosaveinterval" -> GlobalConfig.setAutosaveInterval(Double.parseDouble(value));
                case "keybindconflictwarnings" -> GlobalConfig.setKeybindConflictWarningsEnabled(parseBool(value));
                case "discordpresence" -> GlobalConfig.setDiscordPresence(parseBool(value));
                case "stealthmode" -> GlobalConfig.setStealthMode(parseBool(value));
                case "themecolor" -> GlobalConfig.setThemeColor(ThemeColor.valueOf(value.toUpperCase(Locale.ROOT)));
                default -> { CommandManager.sendMessage("Unknown config key: " + key); return; }
            }
            CommandManager.sendMessage("Set " + key + " to " + value);
        } catch (Exception e) {
            CommandManager.sendMessage("Failed to set " + key + ": " + e.getMessage());
        }
    }

    private boolean parseBool(String v) {
        if (v.equalsIgnoreCase("true") || v.equalsIgnoreCase("on") || v.equals("1")) return true;
        if (v.equalsIgnoreCase("false") || v.equalsIgnoreCase("off") || v.equals("0")) return false;
        throw new IllegalArgumentException("Expected true/false");
    }
}
